### PR TITLE
docs: Add stub docs for languages

### PR DESCRIPTION
**Pull request by nicks**
Hello @ellenkorbes, @jazzdan,

Please review the following commits I made in branch nicks/onboarding:

cd502395dd942dbaa49b9ee468a9922628a192da (2020-02-25 16:57:56 -0500)
docs: Add stub docs for languages

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
this is literally a test to see what people click on

**Comment by nicks** [comment]
(I also thought about adding stubs for PHP and Ruby but maybe that's overkill)

**Comment by ellenkorbes** [comment]
Are we gonna go full _Quest For The Fastest Deployment_ for every language?

**Comment by nicks** [comment]
@ellenkorbes YES, but abbreviated a bit. The current template I'm thinking is:

- Set up a project with docker_build
- Optimize the docker_build
- Set up a project with easy/naive live_update
- Optimize the live_update

But I think the details might need to be tweaked a bit per-language

**Comment by ellenkorbes** [comment]
Got it. Sounds good, looking forward to it. I think education re: Dockerfiles is gonna play a really important role here.

**Pull request merged**
