### PR TITLE
blog: december commit of the month

### PR DESCRIPTION
**Pull request by jazzdan**
Drive link: https://docs.google.com/document/d/1O49X6OPXV1IRejbpk0xky175YDOquGysmF9mTDO1Ld4/edit?usp=sharing

### CODE REVIEW

**Comment by jazzdan** [comment]
When using an svg as the header image it comes out *way* too big at large screen sizes.

Screen Shot 2020-01-02 at 11 40 58 AM

Is there an easy way to limit the size of the svg? cc @hyu @nicks . I tried messing around with different values in the `image_type` section in the front matter but they didn'tseem to make any difference.

**Comment by maiamcc** [comment]
Left some comments in the google doc -- lgtm!

**Comment by nicks** [comment]
lemme see if i can figure out how to cap the header heights, gmas

**Comment by jazzdan** [comment]
any luck @nicks ?

**Comment by nicks** [comment]
try this: https://github.com/windmilleng/tilt.build/pull/376

**Pull request merged**
