### PR TITLE
api: docs for new read_yaml func

### PR DESCRIPTION
**Pull request by maiamcc**
Hello @dmiller, @lredd,

Please review the following commits I made in branch maiamcc/read-yaml-api-doc:

f2c341048ac5b9e2b27bd4246adeebc289edd929 (2019-05-01 11:18:43 -0400)
api: docs for new read_yaml func

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by maiamcc** [comment]
oh damnit @dmiller, I seem to have tagged you again :( i'm off to add a check for this to my [git workflow](https://github.com/dpup/git-workflow) right now.

**Comment by l1redd** [comment]
LGTM

**Comment by dmiller** [comment]
Again, I think you have the wrong Miller.

**Comment by maiamcc** [comment]
Yep, apologies @dmiller. I [made a change to my workflow](https://github.com/dpup/git-workflow/pull/12) so I can stop accidentally tagging you!

**Pull request merged**
