### PR TITLE
blog: Are you my Kustomize? / January Commit of the Month

### PR DESCRIPTION
**Pull request by nicks**
Hello @jazzdan, @l-korbes,

Please review the following commits I made in branch nicks/cotw:

cca5964feb534422954b5377b2966689f19a089c (2020-02-03 19:21:09 -0500)
blog: Are you my Kustomize? / January Commit of the Month

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
@l-korbes good point, probably not. here are a few alternative image options that have the same energy, what do you think?
https://unsplash.com/photos/vBOHVZG6L50
https://unsplash.com/photos/V4UbRPvyaUY

**Comment by nicks** [comment]
photo-1570455679702-0424bae83b1b
photo-1562270529-0efbba66a904

**Comment by nicks** [comment]
used the first one

**Comment by l-korbes** [comment]
Was gonna suggest the second one, but the first works as well :)

**Comment by nicks** [comment]
haha, i changed my mind, switched to the swan!

**Pull request merged**
