### PR TITLE
mention different d4m context names according to d4m version

### PR DESCRIPTION
**Pull request by maiamcc**
In re: [tilt #2193](https://github.com/windmilleng/tilt/issues/2193)

### CODE REVIEW

**Comment by nicks** [comment]
doesn't docker for mac auto-update?

**Comment by maiamcc** [comment]
I mean given that someone complained that they followed our cluster-choosing instructions and it didn't work, apparently at least one person had to enter the other string to make things go...

**Comment by maiamcc** [comment]
Also my d4m asks me every time if i want to update. (sometimes I say no because I'm already on edge and I fear change)

**Comment by maiamcc** [comment]
bump

**Comment by nicks** [comment]
re: "someone complained that they followed our cluster-choosing instructions and it didn't work" - what complaint are you referring to exactly?

**Comment by nicks** [comment]
you're aware that we already updated the instructions after https://github.com/windmilleng/tilt/issues/2193 to use `docker-desktop`, and this pr adds more equivocation

**Comment by maiamcc** [comment]
Oh! Where did we add that documentation?

**Comment by nicks** [comment]
https://github.com/windmilleng/tilt.build/pull/282

i.e., when we closed the ticket

**Comment by maiamcc** [comment]
Oh, I didn't see that PR linked. Okay, will close this.

**Pull request closed without merging**
