### PR TITLE
docs: add a small feedback form on the docs site

### PR DESCRIPTION
**Pull request by nicks**
Hello @jazzdan, @hyu,

Please review the following commits I made in branch nicks/ch1810/helpful:

68d17ceec749591ad26ad479afaa579e398670f0 (2020-02-25 18:37:37 -0500)
docs: add a small feedback form on the docs site

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
Screenshot from 2020-02-25 18-37-29

Right now this just kicks an event into google analytics, though I expect that @victorwuky and leadsleadsleads team will eventually want some better system for aggregating product analytics on the site

**Comment by nicks** [comment]
I have no idea what this meme means 😳

**Comment by victorwuky** [comment]
@nicks : I've verified that this is working on production. See gifs below. Is there a corresponding clubhouse story?

**Comment by victorwuky** [comment]
I also see this data flowing into google analytics. See bottom of this screenshot. Documenting this in https://github.com/windmilleng/company-private/pull/1 now.

Screen Shot 2020-02-26 at 3 10 26 PM

**Comment by nicks** [comment]
@victorwuky yep! for future reference, the clubhouse issue ID is in the branch name
https://app.clubhouse.io/windmill/story/1810/was-this-doc-helpful-button

**Comment by victorwuky** [comment]
Great thanks @nicks !

**Pull request merged**
